apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        component: api-gateway
    spec:
      containers: