apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  MQ_HOST: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLmRlZmF1bHQ6NTY3Mi92aG9zdA==

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: MQ_HOST

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: chapter-title-scaler
spec:
  scaleTargetRef:
    name: chapter-title-deployment
  pollingInterval: 10 # Adjusted polling interval in seconds
  maxReplicaCount: 20 # Adjusted maximum number of replicas
  minReplicaCount: 1  # Optional: minimum number of replicas
  cooldownPeriod: 30  # Optional: cooldown period in seconds
  triggers:
    - type: rabbitmq
      metadata:
        mode: QueueLength
        queueName: scale_out # Ensure this matches your actual queue name
        value: "10"         # Adjusted scaling threshold
      authenticationRef:
        name: rabbitmq-trigger-auth

