apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-frontend
  labels:
    app: client-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-frontend
  template:
    metadata:
      labels:
        app: client-frontend
    spec:
      containers:
      - name: client-frontend
        image: daniel135dang/client 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: client-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
